Repository insightsengineering/random.cdisc.data, pull requests merged in 2023-03, with the labels that each got.

#239 More realistic abnormality directions in `adlb`
  NEWS.md
  R/radlb.R
  data/cadlb.RData
Labels: sme

#249 Add tests, fix grammar
  NEWS.md
  R/radqlqc.R
  R/utils.R
  inst/metadata/ADAB.yml
  tests/testthat/test-rdata.R
  tests/testthat/test-utils.R
Labels: sme

#246 updating README
  NEWS.md
  R/radab.R
  R/radcm.R
  R/radpc.R
  R/radpp.R
  README.md
  _pkgdown.yml
  man/radab.Rd
  man/radcm.Rd
  man/radpc.Rd
  man/radpp.Rd
Labels: documentation, sme

#245 Fix derivations for `AVAL`, `ANRIND`, `*STRESC`, and `LOQFL` in `adlb` and `advs`
  NEWS.md
  R/raddv.R
  R/radlb.R
  R/radvs.R
  data/cadlb.RData
  data/cadvs.RData
  inst/metadata/ADVS.yml
  man/radlb.Rd
Labels: enhancement, sme

#253 Set `object_name_linter = NULL`
  .lintr
  R/radab.R
  R/radae.R
  R/radaette.R
  R/radcm.R
  R/raddv.R
  R/radeg.R
  R/radex.R
  R/radhy.R
  R/radlb.R
  R/radmh.R
  R/radpc.R
  R/radpp.R
  R/radqlqc.R
  R/radqs.R
  R/radrs.R
  R/radsaftte.R
  R/radsl.R
  R/radsub.R
  R/radtr.R
  R/radtte.R
  R/radvs.R
  R/utils.R
Labels: sme

#256 Remove unneeded `.data` prefix
  R/radab.R
  R/radae.R
  R/radaette.R
  R/radcm.R
  R/raddv.R
  R/radeg.R
  R/radex.R
  R/radhy.R
  R/radlb.R
  R/radmh.R
  R/radpc.R
  R/radpp.R
  R/radqlqc.R
  R/radqs.R
  R/radrs.R
  R/radsl.R
  R/radsub.R
  R/radtr.R
  R/radtte.R
  R/radvs.R
  R/random.cdisc.data.R
Labels: sme

#259 Fix ADSL `study_duration_secs` attribute
  R/radae.R
  R/radaette.R
  R/radcm.R
  R/raddv.R
  R/radeg.R
  R/radex.R
  R/radhy.R
  R/radlb.R
  R/radmh.R
  R/radqs.R
  R/radrs.R
  R/radsl.R
  R/radtte.R
  R/radvs.R
  data/cadsl.RData
Labels: sme

#261 Update to testthat v3 and add snapshot tests
  DESCRIPTION
  NEWS.md
  tests/testthat/_snaps/row_values.md
  tests/testthat/test-metadata.R
  tests/testthat/test-rdata.R
  tests/testthat/test-row_values.R
  tests/testthat/test-utils.R
Labels: sme

#260 Fix distribution of IGA data in `adlb` after refactoring
  R/radlb.R
  data/cadlb.RData
  man/radlb.Rd
Labels: bug, sme
